---
- name: Backup vlan.dat to TFTP server
  when: inventory_hostname in groups['switches']
  cisco.ios.ios_command:
    commands:
      - command: "copy flash:vlan.dat tftp://{{ tftp_server_ip }}/{{ tftp_vlan_dat_folder }}/{{ inventory_hostname }}_vlan_{{ timestamp }}.dat"
        prompt:
          - "Address or name of remote host"
          - "Destination filename"
        answer:
          - "\n"
          - "\n"

...
